### ISSUE TITLE
about part 6 HalfCheetah 

### ISSUE THREAD

**Issue by Observerspy** [CSKrishna/CS294#1]
Hi, I noticed that you have finished the cs294 hw2. Did you try the part 6 HalfCheetah-v1? I have some trouble of getting an average score of 150 or more at the end of 100 iterations. If you tried, please let me know. Thanks a lot. :)

**Comment by CSKrishna** [comment]
Hi Observerspy, I haven't tried out HafCheetah because I haven't installed the required Mujo dependency for the HalfCheetah-v1 environment. I have moved on to assignment 3 and plan to revisit HalfCheetah later.

C S Krishna

**Comment by Observerspy** [comment]
Anyway, thanks a lot.
